// The Firebase web config isn't secret, but it still lives in env vars so no
// project's values end up committed. Both `npm run build` and `npm run dev`
// call this, so the generated module always exists before the browser asks
// for it. Missing vars produce `null`, which the app reads as "no online play"
// rather than crashing.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(root, 'src', 'js', 'firebase-config.js');

const KEYS = {
  apiKey: 'FIREBASE_API_KEY',
  authDomain: 'FIREBASE_AUTH_DOMAIN',
  databaseURL: 'FIREBASE_DATABASE_URL',
  projectId: 'FIREBASE_PROJECT_ID',
  storageBucket: 'FIREBASE_STORAGE_BUCKET',
  messagingSenderId: 'FIREBASE_MESSAGING_SENDER_ID',
  appId: 'FIREBASE_APP_ID',
};

function readDotEnv() {
  const file = path.join(root, '.env');
  if (!existsSync(file)) return {};
  const out = {};
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    const m = line.match(/^\s*(?:export\s+)?([A-Z0-9_]+)\s*=\s*(.*)$/);
    if (m) out[m[1]] = m[2].trim().replace(/^["']|["']$/g, '');
  }
  return out;
}

/** Writes src/js/firebase-config.js. Returns true when online play is configured. */
export function writeFirebaseConfig() {
  const env = { ...readDotEnv(), ...process.env }; // real env wins over .env
  const config = {};
  for (const [key, name] of Object.entries(KEYS)) if (env[name]) config[key] = env[name];

  // databaseURL is the only one online play genuinely cannot work without.
  const ok = Boolean(config.apiKey && config.databaseURL && config.projectId);
  writeFileSync(
    OUT,
    '// Generated by scripts/firebase-config.mjs — do not edit, do not commit.\n' +
      `export const firebaseConfig = ${ok ? JSON.stringify(config, null, 2) : 'null'};\n`
  );
  console.log(
    ok
      ? `Firebase config written for project "${config.projectId}" — online play enabled.`
      : 'No FIREBASE_* env vars found — online play will be hidden. See .env.example.'
  );
  return ok;
}
